# Generated by Django 6.0.7 on 2026-09-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='semester',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
